version: '3'
services:
  mysql:
    user: "${CONTAINER_USER}:${CONTAINER_USER}"
    image: mysql:${VERSION}
    volumes:
      - ./mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - databases
    restart: always

networks:
  databases:
    external:
      name: databases
