version: '3'
services:
  mysql:
    user: "${CONTAINER_USER}:${CONTAINER_USER}"
    image: mysql:${VERSION}
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - databases
    restart: always

networks:
  databases:
    external:
      name: databases
